import Head from "next/head";
import Navbar from "../components/Navbar";
import { useState, useEffect } from "react";
import CoinsTable from "../components/Table";
import TrendingNavigation from "../components/TrendingNavigation";
import Footer from "../components/Footer";
import axios from 'axios';

export default function Home() {
    const [isSidebarOpen, setIsSidebarOpen] = useState(true);
    const [topGainersData, setTopGainersData] = useState([]);

    const toggleSidebar = () => {
        setIsSidebarOpen(!isSidebarOpen);
    };

    // Fetch top gainers on component mount
    useEffect(() => {
        async function fetchTopGainers() {
            try {
                const response = await axios.get('/api/topGainers');
                setTopGainersData(response.data);
            } catch (error) {
                console.error('Error fetching top gainers:', error);
            }
        }

        fetchTopGainers();
    }, []);

    return (
        <>
            <Head>
                <title>CoinBoom</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar isSidebarOpen={isSidebarOpen} toggleSidebar={toggleSidebar} />
                <div
                    className={`min-h-screen bg-black text-white p-6 pt-20 transition-all duration-300 ${
                        isSidebarOpen ? "ml-64" : "ml-0"
                    }`}
                >
                    <h2 className="text-2xl font-bold mb-3">Top Gainers</h2>
                    <CoinsTable coinsData={topGainersData} />
                    <h2 className="text-2xl font-bold my-4">Latest Crypto Coins</h2>
                    <TrendingNavigation />
                    <CoinsTable coinsData={topGainersData} />
                </div>
            </main>
            <div
                className={`transition-all duration-300 ${isSidebarOpen ? "ml-64" : "ml-0"}`}
            >
                <Footer />
            </div>
        </>
    );
}
